Catch errors in rsync and show outputs with color

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,6 +2,7 @@
 
 GREEN='\033[32m'
 GREEN_B='\033[42m'
+YELLOW='\033[33m'
 BLINK='\033[5m'
 RESET='\033[0m'
 
@@ -57,7 +58,6 @@ echo -e "\n[ $ORGANIZATION_NAME ]\n"
 echo -e "Auto Deployment to ${GREEN}${SERVER_NAME}${RESET} will be processed in ${GREEN}$(pwd)${RESET}\n"
 
 
-# TIMER_START=$(date +%s)
 # see path of what you're going to deploy. is it right?
 echo -e "[${ITEM}/${ITEMS}] clean-compile-staged ${GREEN}$(pwd)/target${RESET} is okay? [y/n]: "
   while true; do
@@ -71,9 +71,6 @@ echo -e "[${ITEM}/${ITEMS}] clean-compile-staged ${GREEN}$(pwd)/target${RESET} i
     fi
   done
 let ITEM+=1
-# TIMER_END = $(date +%s)
-# TIMER_DIFF=$(( $TIMER_END - $TIMER_START ))
-# echo -e "[${ITEM}/${ITEMS}] Done in ${TIMER_DIFF}s"
 
 # what server and port do you want to deploy?
 echo -e "[${ITEM}/${ITEMS}] Port ${GREEN}${PORT}${RESET} is okay? [y/n]: "
@@ -93,13 +90,22 @@ echo -e "[${ITEM}/${ITEMS}] Waiting for upload ... "
   START=$(date +%s)
 
   # copying
-  rsync -rzu ./target/ trinity@trinity.so:/home/trinity/playframework/.${PORT}
-  
-  END=$(date +%s)
-  DIFF=$(( $END - $START ))
+  echo -e "${YELLOW}"
+  rsync -rzu ./target/ $SERVER_USER@$SERVER_HOST:$BASE_DIR/.${PORT}
+  RSYNC_CODE=$?
+  echo -e "${RESET}"
+
+  if [ $RSYNC_CODE -ne 0 ]
+  then
+    echo -e "error:\tfailed to upload\n\tcheck ${GREEN}${SERVER_USER}@${SERVER_HOST}${RESET} is correct\n"
+    exit
+  else
+    END=$(date +%s)
+    DIFF=$(( $END - $START ))
+    echo -e "${GREEN} Uploaded in ${DIFF}s${RESET}"
+  fi
 
 let ITEM+=1
-echo -e "${GREEN} Uploaded in ${DIFF}s${RESET}"
 echo -e "[${ITEM}/${ITEMS}] Waiting for restart ... "
   # ssh shell script execution
   # 1> /dev/null
